### ISSUE TITLE
State monad

### ISSUE THREAD

**Issue by gilesbradshaw** [learnyouahaskell/learnyouahaskell.github.io#43] opened 2022-12-30 00:13 UTC
**Is your content edit request related to a problem? Please describe.**

Some of the state monad stuff doesnlt comiple as State is not exported from Control.Monad.State

**Describe the solution you'd like**
state in lower case:

```
type Stack = [Int]

pop :: State Stack Int  
pop = state $ \(x:xs) -> (x,xs)  
  
push :: Int -> State Stack ()  
push a = state $ \xs -> ((),a:xs)  

```

**Additional context**

https://stackoverflow.com/questions/9697980/the-state-monad-and-learnyouahaskell-com
**Link to the page in question**

https://learnyouahaskell.github.io/for-a-few-monads-more.html#state

**Comment by MatthijsBlom** [comment] 2022-12-30 01:05
Duplicate of #7.

**Closed** 2023-01-11 00:11 UTC
Labels: enhancement
